### ISSUE TITLE
German vat rate differences with website

### ISSUE THREAD

**Issue by officialmmt** [spaze/vat-calculator#21]
Hi, I try again your package. When I try with Germany it gives %16 vat. But on the website, it is a %19. [Moss rates](https://ec.europa.eu/taxation_customs/business/vat/telecommunications-broadcasting-electronic-services/vat-rates_en)
Is it change with a period of the year?

**Comment by spaze** [comment]
Hi, Germany has temporarily cut the VAT rate until the end of the year, see #3 I don't know why that site shows the original rate.
