### ISSUE TITLE
20% fixed tax

### ISSUE THREAD

**Issue by officialmmt** [spaze/vat-calculator#24]
Hi Michal,

First of all, I would like to thank you. I have been using the package you wrote for two months and I am very satisfied. 

**I had a need. How can I convert to a fixed 20% tax rate for Europe only in the package?**

Thanks in advance for your answer

**Comment by spaze** [comment]
Hi, thanks! :-) Why do you need a fixed tax, what is the case for fixed VAT?

**Comment by officialmmt** [comment]
As you know, there are annual sales volume limits for Moss (starting from 10000 €). Those who do not reach this limit must apply the tax amount of their own country without applying Moss tax scheme. In this case, it will be a need for me and such companies.

**Comment by spaze** [comment]
Can you solve the problem by not setting `$businessCountryCode` in `VatCalculator` constructor or by passing `$company = false` when calling `calculate()`? That might help, if I understand the issue correctly.

**Comment by officialmmt** [comment]
If I do this 20% tax will be applied to the European Union. 0% to others right?

**Comment by spaze** [comment]
`shouldCollectEuVat` would return false for non-EU countries, so you don't even try to calculate VAT as this package only works with EU VAT (and a few exceptions, if configured manually)

**Comment by officialmmt** [comment]
I have previously made the company variable false.
```
$vatRates = new VatRates();
$vatRate = new VatCalculator($vatRates);
$rates = $vatRate->getTaxRateForLocation($code, null, false);
```

**Comment by spaze** [comment]
If I understand it correctly, you want `VatRates::getTaxRateForLocation()` to always return 20%, no matter what `$countryCode` etc is passed? Probably the easiest way would be to use a custom `VatRates` object with a method `getTaxRateForLocation` that would always return what you need and then pass the object to `new VatCalculator(...)`.

I could add `VatRatesInterface` so yo don't need to extend anything. Would that be fine with you?

**Comment by spaze** [comment]
Thinking about it, it seems the best way is to extend `VatRates` and override the method, something like

```php
class FixedVatRate
{
	public function getTaxRateForLocation(string $countryCode, ?string $postalCode, ?string $type = self::GENERAL, ?DateTimeInterface $date = null): float
	{
		return 0.2;
        }
}

$vatRates = new FixedVatRate();
$vatRate = new VatCalculator($vatRates);
```

Does it help?

**Comment by officialmmt** [comment]
I did try like this and always return 0.2 vat rate for Eu and non-Eu countries. If non-EU countries can get 0% vat rate we will reach the goal.

```
use DateTimeInterface;
use Spaze\VatCalculator\VatRates;

class FixedVatRate extends VatRates
{
    public function getTaxRateForLocation(string $countryCode, ?string $postalCode, ?string $type = self::GENERAL, ?DateTimeInterface $date = null): float
    {
        return 0.2;
    }
}
```

**Comment by spaze** [comment]
Sure, you can return whatever you want :-)

**Comment by officialmmt** [comment]
shouldCollectEuVat return boolean so I should handle with if.

**Comment by spaze** [comment]
Indeed. Glad you've found the solution 👍
