### ISSUE TITLE
Composer says: Package spaze/vat-calculator is abandoned

### ISSUE THREAD

**Issue by Fossil01** [spaze/vat-calculator#41]
Package spaze/vat-calculator is abandoned, you should avoid using it. Use driesvints/vat-calculator instead.

Don't think that's true? :-)

**Comment by spaze** [comment]
Unfortunately it is true, there will not be any new releases, at least not by me. Please see the [release notes of the 4(.0.4) release](https://github.com/spaze/vat-calculator/releases/tag/v4.0.4).
